In [1]:
import pandas as pd
import numpy as np
import scipy as sp
import sklearn as sk
import polars as pl
import matplotlib.pyplot as plt
import os
import shutil
from IPython.display import display

# Pre-process Dataset

In [2]:
# Manually download dataset into /docs
# Check files/ File path
DOCS_PATH = "/content/docs"

print("Files in docs folder:", os.listdir(DOCS_PATH))

TRAIN_PATH = os.path.join(DOCS_PATH, "train.parquet")
TEST_PATH = os.path.join(DOCS_PATH, "test.parquet")

# Lazy load
train_df = pl.scan_parquet(TRAIN_PATH)
test_df = pl.scan_parquet(TEST_PATH)

# Print schema
print("Schema:")
print(test_df.schema)

# Get shape (forces minimal computation)
print("Train shape:", train_df.select(pl.count()).collect())
print("Test shape:", test_df.select(pl.count()).collect())
# Preview data (only loads small sample)
display(train_df.head(5).collect())
display(test_df.head(5).collect())

Files in docs folder: ['train.parquet', 'test.parquet']
Schema:
Schema({'id': String, 'code': String, 'sub_code': String, 'sub_category': String, 'horizon': Int32, 'ts_index': Int32, 'feature_a': Int32, 'feature_b': Float64, 'feature_c': Float64, 'feature_d': Float64, 'feature_e': Float64, 'feature_f': Float64, 'feature_g': Float64, 'feature_h': Float64, 'feature_i': Float64, 'feature_j': Float64, 'feature_k': Float64, 'feature_l': Float64, 'feature_m': Float64, 'feature_n': Float64, 'feature_o': Float64, 'feature_p': Float64, 'feature_q': Float64, 'feature_r': Float64, 'feature_s': Float64, 'feature_t': Float64, 'feature_u': Float64, 'feature_v': Float64, 'feature_w': Float64, 'feature_x': Float64, 'feature_y': Float64, 'feature_z': Float64, 'feature_aa': Float64, 'feature_ab': Float64, 'feature_ac': Float64, 'feature_ad': Float64, 'feature_ae': Float64, 'feature_af': Float64, 'feature_ag': Float64, 'feature_ah': Float64, 'feature_ai': Float64, 'feature_aj': Float64, 'feature_ak': Float64, 'feature_al': Float64, 'feature_am': Float64, 'feature_an': Float64, 'feature_ao': Float64, 'feature_ap': Float64, 'feature_aq': Float64, 'feature_ar': Float64, 'feature_as': Float64, 'feature_at': Float64, 'feature_au': Float64, 'feature_av': Float64, 'feature_aw': Float64, 'feature_ax': Float64, 'feature_ay': Float64, 'feature_az': Float64, 'feature_ba': Float64, 'feature_bb': Float64, 'feature_bc': Float64, 'feature_bd': Float64, 'feature_be': Float64, 'feature_bf': Float64, 'feature_bg': Float64, 'feature_bh': Float64, 'feature_bi': Float64, 'feature_bj': Float64, 'feature_bk': Float64, 'feature_bl': Float64, 'feature_bm': Float64, 'feature_bn': Float64, 'feature_bo': Float64, 'feature_bp': Float64, 'feature_bq': Float64, 'feature_br': Float64, 'feature_bs': Float64, 'feature_bt': Float64, 'feature_bu': Float64, 'feature_bv': Float64, 'feature_bw': Float64, 'feature_bx': Float64, 'feature_by': Float64, 'feature_bz': Float64, 'feature_ca': Float64, 'feature_cb': Float64, 'feature_cc': Float64, 'feature_cd': Float64, 'feature_ce': Float64, 'feature_cf': Float64, 'feature_cg': Float64, 'feature_ch': Int64})

/tmp/ipykernel_56196/1787950942.py:16: PerformanceWarning: Resolving the schema of a LazyFrame is a potentially expensive operation. Use `LazyFrame.collect_schema()` to get the schema without this warning.
  print(test_df.schema)
/tmp/ipykernel_56196/1787950942.py:19: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  print("Train shape:", train_df.select(pl.count()).collect())

Train shape: shape: (1, 1)
┌─────────┐
│ count   │
│ ---     │
│ u32     │
╞═════════╡
│ 5337414 │
└─────────┘
Test shape: shape: (1, 1)
┌─────────┐
│ count   │
│ ---     │
│ u32     │
╞═════════╡
│ 1447107 │
└─────────┘

/tmp/ipykernel_56196/1787950942.py:20: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  print("Test shape:", test_df.select(pl.count()).collect())

shape: (5, 94)
┌────────────┬──────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id         ┆ code     ┆ sub_code ┆ sub_categ ┆ … ┆ feature_c ┆ feature_c ┆ y_target  ┆ weight    │
│ ---        ┆ ---      ┆ ---      ┆ ory       ┆   ┆ g         ┆ h         ┆ ---       ┆ ---       │
│ str        ┆ str      ┆ str      ┆ ---       ┆   ┆ ---       ┆ ---       ┆ f64       ┆ f64       │
│            ┆          ┆          ┆ str       ┆   ┆ f64       ┆ i64       ┆           ┆           │
╞════════════╪══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ W2MW3G2L__ ┆ W2MW3G2L ┆ J0G2B0KU ┆ PZ9S1Z4V  ┆ … ┆ 0.112068  ┆ 1         ┆ -0.551324 ┆ 40.982572 │
│ J0G2B0KU__ ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ PZ9S1Z4V__ ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ …          ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ W2MW3G2L__ ┆ W2MW3G2L ┆ J0G2B0KU ┆ PZ9S1Z4V  ┆ … ┆ 0.112068  ┆ 1         ┆ -0.315583 ┆ 150.07540 │
│ J0G2B0KU__ ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆ 6         │
│ PZ9S1Z4V__ ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ …          ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ W2MW3G2L__ ┆ W2MW3G2L ┆ J0G2B0KU ┆ PZ9S1Z4V  ┆ … ┆ 0.112068  ┆ 1         ┆ -0.362894 ┆ 115.95355 │
│ J0G2B0KU__ ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆ 2         │
│ PZ9S1Z4V__ ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ …          ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ W2MW3G2L__ ┆ W2MW3G2L ┆ J0G2B0KU ┆ PZ9S1Z4V  ┆ … ┆ 0.112068  ┆ 1         ┆ -0.667023 ┆ 64.573073 │
│ J0G2B0KU__ ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ PZ9S1Z4V__ ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ …          ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ W2MW3G2L__ ┆ W2MW3G2L ┆ J0G2B0KU ┆ PZ9S1Z4V  ┆ … ┆ 0.109204  ┆ 1         ┆ -0.437398 ┆ 41.948761 │
│ J0G2B0KU__ ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ PZ9S1Z4V__ ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ …          ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
└────────────┴──────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (5, 92)
┌────────────┬──────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id         ┆ code     ┆ sub_code ┆ sub_categ ┆ … ┆ feature_c ┆ feature_c ┆ feature_c ┆ feature_c │
│ ---        ┆ ---      ┆ ---      ┆ ory       ┆   ┆ e         ┆ f         ┆ g         ┆ h         │
│ str        ┆ str      ┆ str      ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆          ┆          ┆ str       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ i64       │
╞════════════╪══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ W2MW3G2L__ ┆ W2MW3G2L ┆ 495MGHFJ ┆ PZ9S1Z4V  ┆ … ┆ -0.25646  ┆ 1.665532  ┆ 0.071324  ┆ 2         │
│ 495MGHFJ__ ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ PZ9S1Z4V__ ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ …          ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ W2MW3G2L__ ┆ W2MW3G2L ┆ 495MGHFJ ┆ PZ9S1Z4V  ┆ … ┆ -0.25646  ┆ 1.665532  ┆ 0.071324  ┆ 2         │
│ 495MGHFJ__ ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ PZ9S1Z4V__ ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ …          ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ W2MW3G2L__ ┆ W2MW3G2L ┆ 495MGHFJ ┆ PZ9S1Z4V  ┆ … ┆ -0.25646  ┆ 1.665532  ┆ 0.071324  ┆ 2         │
│ 495MGHFJ__ ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ PZ9S1Z4V__ ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ …          ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ W2MW3G2L__ ┆ W2MW3G2L ┆ 495MGHFJ ┆ PZ9S1Z4V  ┆ … ┆ -0.25646  ┆ 1.665532  ┆ 0.071324  ┆ 2         │
│ 495MGHFJ__ ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ PZ9S1Z4V__ ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ …          ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ W2MW3G2L__ ┆ W2MW3G2L ┆ 495MGHFJ ┆ PZ9S1Z4V  ┆ … ┆ -0.24224  ┆ 1.67189   ┆ 0.0711    ┆ 2         │
│ 495MGHFJ__ ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ PZ9S1Z4V__ ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ …          ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
└────────────┴──────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [3]:
train_df = (
    pl.scan_parquet(TRAIN_PATH)
    .sort(["code", "ts_index"])
)
# Collect with streaming (key part)
train_df = train_df.collect(streaming=True)

/tmp/ipykernel_56196/3275900051.py:6: DeprecationWarning: the `streaming` parameter was deprecated in 1.25.0; use `engine` instead.
  train_df = train_df.collect(streaming=True)

In [4]:
num_cols = [col for col in train_df.columns if col not in ["code", "ts_index"]]

# Forward fill
train_df = train_df.with_columns([
    pl.col(col)
    .fill_null(strategy="forward")
    .over("code")
    .alias(col)
    for col in num_cols
])

# Median imputation
train_df = train_df.with_columns([
    pl.col(col)
    .fill_null(pl.col(col).median().over("code"))
    .alias(col)
    for col in num_cols
])

Summary Statistics

In [5]:
print(train_df.describe())

shape: (9, 95)
┌────────────┬───────────┬──────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ id        ┆ code     ┆ sub_code ┆ … ┆ feature_c ┆ feature_c ┆ y_target  ┆ weight    │
│ ---        ┆ ---       ┆ ---      ┆ ---      ┆   ┆ g         ┆ h         ┆ ---       ┆ ---       │
│ str        ┆ str       ┆ str      ┆ str      ┆   ┆ ---       ┆ ---       ┆ f64       ┆ f64       │
│            ┆           ┆          ┆          ┆   ┆ f64       ┆ f64       ┆           ┆           │
╞════════════╪═══════════╪══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 5337414   ┆ 5337414  ┆ 5337414  ┆ … ┆ 5.337414e ┆ 5.337414e ┆ 5.337414e ┆ 5.337414e │
│            ┆           ┆          ┆          ┆   ┆ 6         ┆ 6         ┆ 6         ┆ 6         │
│ null_count ┆ 0         ┆ 0        ┆ 0        ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ mean       ┆ null      ┆ null     ┆ null     ┆ … ┆ 1.061423  ┆ 2.323426  ┆ -0.665905 ┆ 1.6428e7  │
│ std        ┆ null      ┆ null     ┆ null     ┆ … ┆ 1.30505   ┆ 2.092968  ┆ 32.527642 ┆ 6.0271e9  │
│ min        ┆ 10BAVIDU_ ┆ 10BAVIDU ┆ 00983NVP ┆ … ┆ 0.016065  ┆ 0.0       ┆ -2201.881 ┆ 0.0       │
│            ┆ _236HB58W ┆          ┆          ┆   ┆           ┆           ┆ 578       ┆           │
│            ┆ __DPPUO5X ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│            ┆ 2__…      ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ 25%        ┆ null      ┆ null     ┆ null     ┆ … ┆ 0.080401  ┆ 1.0       ┆ -0.129078 ┆ 15.533777 │
│ 50%        ┆ null      ┆ null     ┆ null     ┆ … ┆ 0.159999  ┆ 2.0       ┆ -0.000577 ┆ 1699.3845 │
│            ┆           ┆          ┆          ┆   ┆           ┆           ┆           ┆ 59        │
│ 75%        ┆ null      ┆ null     ┆ null     ┆ … ┆ 1.991461  ┆ 3.0       ┆ 0.051068  ┆ 164190.92 │
│            ┆           ┆          ┆          ┆   ┆           ┆           ┆           ┆ 6981      │
│ max        ┆ X9BZ68VQ_ ┆ X9BZ68VQ ┆ ZYW0W9R9 ┆ … ┆ 10.564406 ┆ 10.0      ┆ 2314.4111 ┆ 1.3912e13 │
│            ┆ _ZT5R1WKA ┆          ┆          ┆   ┆           ┆           ┆ 52        ┆           │
│            ┆ __V8BKY1I ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│            ┆ V__…      ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
└────────────┴───────────┴──────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

Feature Distributions

In [10]:
#need to fix first 2 charts
sample_df = train_df.select(num_cols[:3]).sample(5000)

for col in num_cols[:3]:
    values = sample_df[col].to_numpy()

    plt.figure()
    plt.hist(values, bins=50)
    plt.title(f"Distribution of {col} (sampled)")
    plt.show()

KeyboardInterrupt: